/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class InterfazManager extends javax.swing.JFrame {

    /**
     * Creates new form InterfazManager
     */
    public InterfazManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        BtnMaterialesBajos = new javax.swing.JButton();
        TxtBusqueda = new javax.swing.JTextField();
        BtnRegistoArticulo = new javax.swing.JButton();
        BtnCopiaSeguridad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnProveedores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnRegistroVentas = new javax.swing.JButton();
        BtnEditarMaterial = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        BtnRegistroAyudantes = new javax.swing.JButton();
        BtnRegistroVehiculos = new javax.swing.JButton();
        BtnInventario = new javax.swing.JButton();
        BtnRegistroUsuarios = new javax.swing.JButton();
        LabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaArticulos);

        BtnMaterialesBajos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/advertencia.png"))); // NOI18N
        BtnMaterialesBajos.setText("Materiales Agotados o Bajos");

        BtnRegistoArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/addarticulo.png"))); // NOI18N
        BtnRegistoArticulo.setText("Registro de Articulos");

        BtnCopiaSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/backup.png"))); // NOI18N
        BtnCopiaSeguridad.setText("Copia de Seguridad");

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel1.setText("Lista De Materiales");

        BtnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/contacto.png"))); // NOI18N
        BtnProveedores.setText("Proveedores");

        jLabel2.setText("Buscar Material Codigo/Nombre");

        BtnRegistroVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/registro.png"))); // NOI18N
        BtnRegistroVentas.setText("Registro De Ventas");

        BtnEditarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/edicion.png"))); // NOI18N
        BtnEditarMaterial.setText("Editar Articulo");

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/buscar.png"))); // NOI18N
        BtnBuscar.setText("Buscar");

        BtnRegistroAyudantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/trabajador.png"))); // NOI18N
        BtnRegistroAyudantes.setText("Registro de Ayudantes");

        BtnRegistroVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/vehiculos.png"))); // NOI18N
        BtnRegistroVehiculos.setText("Registro de Vehiculos");

        BtnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/Inventory.png"))); // NOI18N
        BtnInventario.setText("Inventario");

        BtnRegistroUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/users.png"))); // NOI18N
        BtnRegistroUsuarios.setText("Registro de Usuarios");

        LabelTotal.setText("TOTAL REGISTROS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnRegistoArticulo)
                                .addGap(55, 55, 55)
                                .addComponent(BtnRegistroUsuarios)
                                .addGap(65, 65, 65)
                                .addComponent(BtnRegistroVehiculos)
                                .addGap(57, 57, 57)
                                .addComponent(BtnProveedores))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnInventario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnMaterialesBajos))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(BtnRegistroVentas)))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnRegistroAyudantes)
                                        .addGap(71, 71, 71)
                                        .addComponent(BtnCopiaSeguridad))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnEditarMaterial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnBuscar))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTotal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistoArticulo)
                    .addComponent(BtnRegistroUsuarios)
                    .addComponent(BtnRegistroVehiculos)
                    .addComponent(BtnProveedores))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistroVentas)
                    .addComponent(BtnRegistroAyudantes)
                    .addComponent(BtnCopiaSeguridad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInventario)
                    .addComponent(BtnMaterialesBajos)
                    .addComponent(TxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnEditarMaterial))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTotal)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCopiaSeguridad;
    private javax.swing.JButton BtnEditarMaterial;
    private javax.swing.JButton BtnInventario;
    private javax.swing.JButton BtnMaterialesBajos;
    private javax.swing.JButton BtnProveedores;
    private javax.swing.JButton BtnRegistoArticulo;
    private javax.swing.JButton BtnRegistroAyudantes;
    private javax.swing.JButton BtnRegistroUsuarios;
    private javax.swing.JButton BtnRegistroVehiculos;
    private javax.swing.JButton BtnRegistroVentas;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JTextField TxtBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JButton BtnBuscar() {
        return BtnBuscar;
    }

    public void setDatos(DefaultTableModel modeloTabla, int total) {
        TablaArticulos.setModel(modeloTabla);
        LabelTotal.setText("Total Registros: " + total);
    }

    public JButton BtnEditarMaterial() {
        return BtnEditarMaterial;
    }

    public JButton BtnInventario() {
        return BtnInventario;
    }

    public JButton BtnMaterialBajo() {
        return BtnMaterialesBajos;
    }

    public JButton BtnProveedor() {
        return BtnProveedores;
    }

    public JButton BtnRegistroArticulo() {
        return BtnRegistoArticulo;
    }

    public JButton BtnRegistroAyudante() {
        return BtnRegistroAyudantes;
    }

    public JButton BtnRegistroUsuario() {
        return BtnRegistroUsuarios;
    }

    public JButton BtnRegistroVehiculos() {
        return BtnRegistroVehiculos;
    }

    public JButton BtnVentas() {
        return BtnRegistroVentas;
    }

    public JButton BtnBackup() {
        return BtnCopiaSeguridad;
    }

    public JTextField TxtBusqueda() {
        return TxtBusqueda;
    }
}
