/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JMenuItem;


/**
 *
 * @author HP
 */
public class InterfazManager extends javax.swing.JFrame {

    /**
     * Creates new form InterfazManager
     */
    public InterfazManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemMateriales = new javax.swing.JMenuItem();
        ItemAyudantes = new javax.swing.JMenuItem();
        ItemVehiculos = new javax.swing.JMenuItem();
        ItemRegistroVehiculos = new javax.swing.JMenuItem();
        ItemVentas = new javax.swing.JMenuItem();
        ItemProveedor = new javax.swing.JMenuItem();
        Separador = new javax.swing.JPopupMenu.Separator();
        ItemUsuarios = new javax.swing.JMenuItem();
        ItemBackup = new javax.swing.JMenuItem();
        ItemSesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setBackground(new java.awt.Color(255, 153, 102));

        jMenu1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu1.setText("TALLER MECANICO CONDORI");
        jMenu1.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(375, 25));

        ItemMateriales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        ItemMateriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/material.png"))); // NOI18N
        ItemMateriales.setText("ADMINISTRAR MATERIALES");
        jMenu1.add(ItemMateriales);

        ItemAyudantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        ItemAyudantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/ayudante.png"))); // NOI18N
        ItemAyudantes.setText("ADMINISTRAR AYUDANTES");
        jMenu1.add(ItemAyudantes);

        ItemVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        ItemVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/vehiculo.png"))); // NOI18N
        ItemVehiculos.setText("ADMINISTRAR VEHICULOS");
        ItemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemVehiculosActionPerformed(evt);
            }
        });
        jMenu1.add(ItemVehiculos);

        ItemRegistroVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        ItemRegistroVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/reparacion.png"))); // NOI18N
        ItemRegistroVehiculos.setText("REGISTRAR INGRESO DE VEHICULO AL TALLER");
        jMenu1.add(ItemRegistroVehiculos);

        ItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ItemVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/venta.png"))); // NOI18N
        ItemVentas.setText("ADMINISTRAR VENTAS A CLIENTE");
        jMenu1.add(ItemVentas);

        ItemProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        ItemProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/proveedor.png"))); // NOI18N
        ItemProveedor.setText("ADMINISTRAR PROVEEDORES");
        ItemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(ItemProveedor);
        jMenu1.add(Separador);

        ItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        ItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/user.png"))); // NOI18N
        ItemUsuarios.setText("REGISTRAR NUEVO USUARIO");
        jMenu1.add(ItemUsuarios);

        ItemBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        ItemBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/backup.png"))); // NOI18N
        ItemBackup.setText("COPIA DE SEGURIDAD");
        jMenu1.add(ItemBackup);

        ItemSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        ItemSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/cerrar.png"))); // NOI18N
        ItemSesion.setText("CERRAR SESION");
        jMenu1.add(ItemSesion);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemVehiculosActionPerformed

    private void ItemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAyudantes;
    private javax.swing.JMenuItem ItemBackup;
    private javax.swing.JMenuItem ItemMateriales;
    private javax.swing.JMenuItem ItemProveedor;
    private javax.swing.JMenuItem ItemRegistroVehiculos;
    private javax.swing.JMenuItem ItemSesion;
    private javax.swing.JMenuItem ItemUsuarios;
    private javax.swing.JMenuItem ItemVehiculos;
    private javax.swing.JMenuItem ItemVentas;
    private javax.swing.JPopupMenu.Separator Separador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JMenuItem ItemAyudantes(){
        return ItemAyudantes;
    }
    public JMenuItem ItemBackup(){
        return ItemBackup;
    }
   
    public JMenuItem ItemMateriales(){
        return ItemMateriales;
    }
    public JMenuItem ItemProveedor(){
        return ItemProveedor;
    }
    public JMenuItem ItemIngresoVehiculos(){
        return ItemRegistroVehiculos;
    }
    public JMenuItem ItemSesion(){
        return ItemSesion;
    }
    public JMenuItem ItemUsuarios(){
        return ItemUsuarios;
    }
    public JMenuItem ItemVehiculos(){
        return ItemVehiculos;
    }
    
    public JMenuItem ItemVentas(){
        return ItemVentas;
    }
    
}
