/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class DetallesDeVentas extends javax.swing.JPanel {

    /**
     * Creates new form DetallesDeVentas
     */
    public DetallesDeVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnEntregas = new javax.swing.JButton();
        BtnVentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArticulos = new javax.swing.JTable();
        BtnActualizar = new javax.swing.JButton();
        TxtBusqueda = new javax.swing.JTextField();
        LabelTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel1.setText("Control de Ingresos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 11, -1, -1));

        jLabel2.setText("Buscar Por Codigo Material :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 116, -1, -1));

        BtnEntregas.setBackground(new java.awt.Color(102, 255, 255));
        BtnEntregas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/advertencia.png"))); // NOI18N
        BtnEntregas.setText("Detalles de Entregas a Taller");
        add(BtnEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        BtnVentas.setBackground(new java.awt.Color(102, 255, 255));
        BtnVentas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Manager/advertencia.png"))); // NOI18N
        BtnVentas.setText("Detalles de Ventas");
        add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        TablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaArticulos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 1050, 447));

        BtnActualizar.setBackground(new java.awt.Color(204, 204, 204));
        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paneles/Imagenes/refresh.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 103, -1, -1));
        add(TxtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 113, 112, -1));

        LabelTotal.setText("TOTAL REGISTROS");
        add(LabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, 19));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnEntregas;
    private javax.swing.JButton BtnVentas;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable TablaArticulos;
    private javax.swing.JTextField TxtBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JTable TablaArticulos() {
        return TablaArticulos;
    }

    public void setDatos(DefaultTableModel modeloTabla, int total) {
        TablaArticulos.setModel(modeloTabla);
        LabelTotal.setText("Total Registros: " + total);
    }
    public JButton BtnActualizar() {
        return BtnActualizar;
    }

    public JTextField TxtBusqueda() {
        return TxtBusqueda;
    }
    public JButton BtnVentas(){
        return BtnVentas;
    }
    public JButton BtnEntregas(){
        return BtnEntregas;
    }
  

}
